--- gradlew (原始)
#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#           noncompliant, but you have some other compliant shell such as ksh or
#           bash, then to run this script, type that shell name before the whole
#           command line, like:
#
#               ksh Gradle
#
#           Busybox and similar reduced shells will NOT work, because this script
#           requires all of these POSIX shell features:
#             * functions;
#             * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#               «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#             * compound commands having a testable exit status, especially «case»;
#             * various built-in commands including «command», «set», and «ulimit».
#
#           Important for patching:
#
#           (2) This script targets any POSIX shell, so it avoids extensions provided
#               by Bash, Ksh, etc; in particular arrays are avoided.
#
#               The "traditional" practice of packing multiple parameters into a
#               space-separated string is a well documented source of bugs and security
#               problems, so this is (mostly) avoided, by progressively accumulating
#               options in "$@", and eventually passing that to Java.
#
#               Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#               and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#               see the in-line comments for details.
#
#               There are tweaks for specific operating systems such as AIX, CygWin,
#               Darwin, MinGW, and NonStop.
#
#               (3) This script is generated from the Groovy template
#                   https://github.com/gradle/gradle/blob/HEAD/platform/jvm/plugins/application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#                   within the Gradle project.
#
#               You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"

+++ gradlew (修改后)
     1	#!/bin/sh
     2	
     3	##############################################################################
     4	#
     5	#   Gradle start up script for POSIX generated by Gradle.
     6	#
     7	#   Important for running:
     8	#
     9	#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
    10	#           noncompliant, but you have some other compliant shell such as ksh or
    11	#           bash, then to run this script, type that shell name before the whole
    12	#           command line, like:
    13	#
    14	#               ksh Gradle
    15	#
    16	#           Busybox and similar reduced shells will NOT work, because this script
    17	#           requires all of these POSIX shell features:
    18	#             * functions;
    19	#             * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
    20	#               «${var#prefix}», «${var%suffix}», and «$( cmd )»;
    21	#             * compound commands having a testable exit status, especially «case»;
    22	#             * various built-in commands including «command», «set», and «ulimit».
    23	#
    24	#           Important for patching:
    25	#
    26	#           (2) This script targets any POSIX shell, so it avoids extensions provided
    27	#               by Bash, Ksh, etc; in particular arrays are avoided.
    28	#
    29	#               The "traditional" practice of packing multiple parameters into a
    30	#               space-separated string is a well documented source of bugs and security
    31	#               problems, so this is (mostly) avoided, by progressively accumulating
    32	#               options in "$@", and eventually passing that to Java.
    33	#
    34	#               Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
    35	#               and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
    36	#               see the in-line comments for details.
    37	#
    38	#               There are tweaks for specific operating systems such as AIX, CygWin,
    39	#               Darwin, MinGW, and NonStop.
    40	#
    41	#               (3) This script is generated from the Groovy template
    42	#                   https://github.com/gradle/gradle/blob/HEAD/platform/jvm/plugins/application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
    43	#                   within the Gradle project.
    44	#
    45	#               You can find Gradle at https://github.com/gradle/gradle/.
    46	#
    47	##############################################################################
    48	
    49	# Attempt to set APP_HOME
    50	
    51	# Resolve links: $0 may be a link
    52	app_path=$0
    53	
    54	# Need this for daisy-chained symlinks.
    55	while
    56	    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    57	    [ -h "$app_path" ]
    58	do
    59	    ls=$( ls -ld "$app_path" )
    60	    link=${ls#*' -> '}
    61	    case $link in             #(
    62	      /*)   app_path=$link ;; #(
    63	      *)    app_path=$APP_HOME$link ;;
    64	    esac
    65	done
    66	
    67	# This is normally unused
    68	# shellcheck disable=SC2034
    69	APP_BASE_NAME=${0##*/}
    70	APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
    71	
    72	# Use the maximum available, or set MAX_FD != -1 to use that value.
    73	MAX_FD=maximum
    74	
    75	warn () {
    76	    echo "$*"
    77	} >&2
    78	
    79	die () {
    80	    echo
    81	    echo "$*"
    82	    echo
    83	    exit 1
    84	} >&2
    85	
    86	# OS specific support (must be 'true' or 'false').
    87	cygwin=false
    88	msys=false
    89	darwin=false
    90	nonstop=false
    91	case "$( uname )" in                #(
    92	  CYGWIN* )         cygwin=true  ;; #(
    93	  Darwin* )         darwin=true  ;; #(
    94	  MSYS* | MINGW* )  msys=true    ;; #(
    95	  NONSTOP* )        nonstop=true ;;
    96	esac
    97	
    98	CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
    99	
   100	
   101	# Determine the Java command to use to start the JVM.
   102	if [ -n "$JAVA_HOME" ] ; then
   103	    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
   104	        # IBM's JDK on AIX uses strange locations for the executables
   105	        JAVACMD=$JAVA_HOME/jre/sh/java
   106	    else
   107	        JAVACMD=$JAVA_HOME/bin/java
   108	    fi
   109	    if [ ! -x "$JAVACMD" ] ; then
   110	        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
   111	
   112	Please set the JAVA_HOME variable in your environment to match the
   113	location of your Java installation."
   114	    fi
   115	else
   116	    JAVACMD=java
   117	    if ! command -v java >/dev/null 2>&1
   118	    then
   119	        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
   120	
   121	Please set the JAVA_HOME variable in your environment to match the
   122	location of your Java installation."
   123	    fi
   124	fi
   125	
   126	# Increase the maximum file descriptors if we can.
   127	if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
   128	    case $MAX_FD in #(
   129	      max*)
   130	        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
   131	        # shellcheck disable=SC3045
   132	        MAX_FD=$( ulimit -H -n ) ||
   133	            warn "Could not query maximum file descriptor limit"
   134	    esac
   135	    case $MAX_FD in  #(
   136	      '' | soft) :;; #(
   137	      *)
   138	        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
   139	        # shellcheck disable=SC3045
   140	        ulimit -n "$MAX_FD" ||
   141	            warn "Could not set maximum file descriptor limit to $MAX_FD"
   142	    esac
   143	fi
   144	
   145	# Collect all arguments for the java command, stacking in reverse order:
   146	#   * args from the command line
   147	#   * the main class name
   148	#   * -classpath
   149	#   * -D...appname settings
   150	#   * --module-path (only if needed)
   151	#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.
   152	
   153	# For Cygwin or MSYS, switch paths to Windows format before running java
   154	if "$cygwin" || "$msys" ; then
   155	    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
   156	    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
   157	
   158	    JAVACMD=$( cygpath --unix "$JAVACMD" )
   159	
   160	    # Now convert the arguments - kludge to limit ourselves to /bin/sh
   161	    for arg do
   162	        if
   163	            case $arg in                                #(
   164	              -*)   false ;;                            # don't mess with options #(
   165	              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
   166	                    [ -e "$t" ] ;;                      #(
   167	              *)    false ;;
   168	            esac
   169	        then
   170	            arg=$( cygpath --path --ignore --mixed "$arg" )
   171	        fi
   172	        # Roll the args list around exactly as many times as the number of
   173	        # args, so each arg winds up back in the position where it started, but
   174	        # possibly modified.
   175	        #
   176	        # NB: a `for` loop captures its iteration list before it begins, so
   177	        # changing the positional parameters here affects neither the number of
   178	        # iterations, nor the values presented in `arg`.
   179	        shift                   # remove old arg
   180	        set -- "$@" "$arg"      # push replacement arg
   181	    done
   182	fi
   183	
   184	
   185	# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
   186	DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
   187	
   188	# Collect all arguments for the java command;
   189	#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
   190	#     shell script including quotes and variable substitutions, so put them in
   191	#     double quotes to make sure that they get re-expanded; and
   192	#   * put everything else in single quotes, so that it's not re-expanded.
   193	
   194	set -- \
   195	        "-Dorg.gradle.appname=$APP_BASE_NAME" \
   196	        -classpath "$CLASSPATH" \
   197	        org.gradle.wrapper.GradleWrapperMain \
   198	        "$@"
   199	
   200	# Stop when "xargs" is not available.
   201	if ! command -v xargs >/dev/null 2>&1
   202	then
   203	    die "xargs is not available"
   204	fi
   205	
   206	# Use "xargs" to parse quoted args.
   207	#
   208	# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
   209	#
   210	# In Bash we could simply go:
   211	#
   212	#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
   213	#   set -- "${ARGS[@]}" "$@"
   214	#
   215	# but POSIX shell has neither arrays nor command substitution, so instead we
   216	# post-process each arg (as a line of input to sed) to backslash-escape any
   217	# character that might be a shell metacharacter, then use eval to reverse
   218	# that process (while maintaining the separation between arguments), and wrap
   219	# the whole thing up as a single "set" statement.
   220	#
   221	# This will of course break if any of these variables contains a newline or
   222	# an unmatched quote.
   223	#
   224	
   225	eval "set -- $(
   226	        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
   227	        xargs -n1 |
   228	        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
   229	        tr '\n' ' '
   230	    )" '"$@"'
   231	
   232	exec "$JAVACMD" "$@"
   233	
